// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: gRPC/proto.proto

package gRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartArgawala_Request_FullMethodName   = "/RicartArgawala.RicartArgawala/request"
	RicartArgawala_EnterCS_FullMethodName   = "/RicartArgawala.RicartArgawala/EnterCS"
	RicartArgawala_ReleaseCS_FullMethodName = "/RicartArgawala.RicartArgawala/ReleaseCS"
)

// RicartArgawalaClient is the client API for RicartArgawala service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartArgawalaClient interface {
	// call this to request permission
	Request(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
	// Ask to attempt entering the critical section
	EnterCS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
	// Ask to release the critical section
	ReleaseCS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error)
}

type ricartArgawalaClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartArgawalaClient(cc grpc.ClientConnInterface) RicartArgawalaClient {
	return &ricartArgawalaClient{cc}
}

func (c *ricartArgawalaClient) Request(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RicartArgawala_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartArgawalaClient) EnterCS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RicartArgawala_EnterCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartArgawalaClient) ReleaseCS(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, RicartArgawala_ReleaseCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartArgawalaServer is the server API for RicartArgawala service.
// All implementations must embed UnimplementedRicartArgawalaServer
// for forward compatibility.
type RicartArgawalaServer interface {
	// call this to request permission
	Request(context.Context, *Message) (*Response, error)
	// Ask to attempt entering the critical section
	EnterCS(context.Context, *Empty) (*Response, error)
	// Ask to release the critical section
	ReleaseCS(context.Context, *Empty) (*Response, error)
	mustEmbedUnimplementedRicartArgawalaServer()
}

// UnimplementedRicartArgawalaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartArgawalaServer struct{}

func (UnimplementedRicartArgawalaServer) Request(context.Context, *Message) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRicartArgawalaServer) EnterCS(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnterCS not implemented")
}
func (UnimplementedRicartArgawalaServer) ReleaseCS(context.Context, *Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCS not implemented")
}
func (UnimplementedRicartArgawalaServer) mustEmbedUnimplementedRicartArgawalaServer() {}
func (UnimplementedRicartArgawalaServer) testEmbeddedByValue()                        {}

// UnsafeRicartArgawalaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartArgawalaServer will
// result in compilation errors.
type UnsafeRicartArgawalaServer interface {
	mustEmbedUnimplementedRicartArgawalaServer()
}

func RegisterRicartArgawalaServer(s grpc.ServiceRegistrar, srv RicartArgawalaServer) {
	// If the following call pancis, it indicates UnimplementedRicartArgawalaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartArgawala_ServiceDesc, srv)
}

func _RicartArgawala_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgawalaServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgawala_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgawalaServer).Request(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartArgawala_EnterCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgawalaServer).EnterCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgawala_EnterCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgawalaServer).EnterCS(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartArgawala_ReleaseCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgawalaServer).ReleaseCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgawala_ReleaseCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgawalaServer).ReleaseCS(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartArgawala_ServiceDesc is the grpc.ServiceDesc for RicartArgawala service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartArgawala_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RicartArgawala.RicartArgawala",
	HandlerType: (*RicartArgawalaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request",
			Handler:    _RicartArgawala_Request_Handler,
		},
		{
			MethodName: "EnterCS",
			Handler:    _RicartArgawala_EnterCS_Handler,
		},
		{
			MethodName: "ReleaseCS",
			Handler:    _RicartArgawala_ReleaseCS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/proto.proto",
}
